Fix WMAgent rpm dcoker image
dmwm/CMSKubernetes pull request #1362
Opened 2023-04-21 14:26 UTC by todor-ivanov

Do NO merge Yet. 

The current PR is intended only to fix the old RPM based Docker image. so that we can test it and reuse bits of it in the new Pypi based setup.

2023-05-18 14:52 UTC, amaltaro requested changes
@todor-ivanov Todor, I assume you wanted to update this deployment model to the recent changes we had in WMCore, so I left a few comments along the code for your consideration.

2023-05-18 14:52 UTC, amaltaro commented on docker/wmagent/install.sh
> -wget -nv -O deployment.zip --no-check-certificate https://github.com/dmwm/deployment/archive/$DEPLOY_TAG.zip
Todor, if I pass `master` as the DEPLOY_TAG, this line seems to work just fine. And so it does for an old HG tag. Do we really need to change this github url?

2023-05-18 14:52 UTC, amaltaro commented on docker/wmagent/Dockerfile
> +ARG WMA_TAG=None
Where does `WMA_TAG` come from? Shouldn't this be using the ENV keyword instead of ARG?

2023-05-18 14:52 UTC, amaltaro commented on docker/wmagent/Dockerfile
> +FROM registry.cern.ch/cmsweb/cmsweb:20221130-stable
I think we have a more recent cmsweb image. I'd suggest to update it to the latest.

2023-05-22 11:09 UTC, todor-ivanov commented
Hi @amaltaro thanks for looking into this PR as well. 

This one was actually just for me, to keep track of all the changes I had to do in order to make this old deployment method work and then use it as initial investigation on how to continue with the Python based docker image. If we want we may finalize this of course. Up to us.

2025-05-05 22:58 UTC, amaltaro commented
@todor-ivanov I guess this is no longer relevant. If so, should we close this out?

2025-05-06 07:59 UTC, todor-ivanov commented
I believe so. Closing it now.

2025-05-06 07:59 UTC, closed without merging