Tune MariaDB settings for better performance
dmwm/CMSKubernetes pull request #1475
Opened 2024-05-10 13:22 UTC by khurtado

Tune MariaDB settings for better performance
More details: https://github.com/dmwm/WMCore/issues/11977

2024-05-10 19:47 UTC, amaltaro commented
@khurtado can this 8GB pool be a problem when we run MariaDB in small nodes (e.g. with <= 8GB of memory RAM)?

I would suggest linking the tests documentation to this PR as well.

2024-05-13 05:15 UTC, todor-ivanov approved these changes
looks good

2024-05-13 13:32 UTC, khurtado commented
@amaltaro That's a good point. I added some commented lines and updated the documentation for it.

An alternative to having the users uncomment settings for small nodes would be to create another branch specially for testbed hardware, but if this is the only change needed in general, for the containerized deployment, then I don't think it is necessary right now.

2024-05-13 21:36 UTC, amaltaro requested changes
@khurtado Kenyi, in addition to the few comments along the code, you might want to add to the PR description that an increase of X% is seen with such configuration (keeping a link to the full tests and results, as you already did).

2024-05-13 21:36 UTC, amaltaro commented on docker/pypi/wmagent-mariadb/README.md
> +#### Building MariaDB on small nodes (e.g.: testbed)
Perhaps change from "Building" to "Running"?

2024-05-13 21:36 UTC, amaltaro commented on docker/pypi/wmagent-mariadb/my.cnf
> +# https://gitlab.cern.ch/dmwm/wmcore-docs/-/blob/master/docs/wmcore/MariaDB-benchmark-tests.md
This link needs to be fixed.

2024-05-15 00:51 UTC, khurtado commented
> @khurtado Kenyi, in addition to the few comments along the code, you might want to add to the PR description that an increase of X% is seen with such configuration (keeping a link to the full tests and results, as you already did).

Done!

2024-05-16 20:42 UTC, amaltaro commented
Thanks Kenyi!

2024-05-16 20:42 UTC, merged