WMAgent: change certs mount point
dmwm/CMSKubernetes pull request #1480
Opened 2024-05-17 00:17 UTC by amaltaro

Fixes https://github.com/dmwm/WMCore/issues/11987

Instead of mounting the certificates from `HOST_MOUNT_DIR` environment variable (set to /data/dockerMount), use the upper directory, such that it reflects the same proxy path between the host and the container.

2024-05-17 05:25 UTC, todor-ivanov commented on docker/pypi/wmagent/wmagent-docker-run.sh
> +--mount type=bind,source=$HOST_MOUNT_DIR/../certs,target=/data/certs \
hi @amaltaro 
Provided we now know there is requirement for absolute match of the mount point and host path, I am more in favor of: 
```
--mount type=bind,source=/data/certs,target=/data/certs \
```

2024-05-17 05:27 UTC, todor-ivanov requested changes
Alan, I left one comment inline. Please take a look

2024-05-17 13:33 UTC, amaltaro commented
I totally agree with that! But whenever I do so, people complain that I am hard-coding things :P
@todor-ivanov code has been updated.

2024-05-17 14:36 UTC, todor-ivanov commented
thanks @amaltaro 
> I totally agree with that! But whenever I do so, people complain that I am hard-coding things :P

I  am usually the one to complain the most about this, but this time I think we have a strong case.

2024-05-18 13:33 UTC, amaltaro commented
@todor-ivanov I think you forgot to approve this, but please let me know if there was anything else missing.
I am merging it such that we can release a new version with all the fixes that went in in the last 48h or so. Thanks

2024-05-18 13:33 UTC, merged