Adding livenessprobe to cmsweb services
dmwm/CMSKubernetes pull request #350
Opened 2020-10-23 06:35 UTC by muhammadimranfarooqi

2020-10-23 08:44 UTC, muhammadimranfarooqi commented
@vkuznet 

How can I test this for das-server, wmarchive and exitcodes? I mean is there any alternative commands similar to this? 

`sudo -H -u _das bashs -l -c '/data/srv/current/config/das/manage status'`

Thanks

2020-10-23 11:14 UTC, vkuznet requested changes
And, there is no manage status command. If you want to test das-server or wmarchive, you can use plain curl against /das/status or /wamrchive/data/ end-points. curl with 200 OK tells you that they are fine.

2020-10-23 11:14 UTC, vkuznet commented on kubernetes/cmsweb/services/das-server.yaml
> +        livenessProbe:
@muhammadimranfarooqi it seems to me you duplicated livenessProbe in das-server which I added before and now it appears now twice. Pease check and fix.

2020-10-23 11:14 UTC, vkuznet commented on kubernetes/cmsweb/services/wmarchive.yaml
> +        livenessProbe:
You duplicated livenessProbe in wmarchive which I added before, see line 76. Please check and fix.

2020-10-23 13:37 UTC, muhammadimranfarooqi commented
@vkuznet 

I have applied requested changes.  

Actually I wanted to ask the alternative of this command. 

`sudo -H -u _das bashs -l -c '/data/srv/current/config/das/manage stop "I did read documentation"'`

If I stop the process inside the pod, k8s kills the container and exits the user from the pod. How can we stop das-server without being killed. In this way, livenessprobe can be tested.

2020-10-23 13:40 UTC, merged

2020-10-23 13:51 UTC, vkuznet commented
SO, in case of das-server you may login to the pod
```
/ # ps
PID   USER     TIME  COMMAND
    1 root      0:00 {run.sh} /bin/sh /data/run.sh
    7 root      0:37 /data/das2go_exporter -address :18217
    8 root     36:26 /data/das2go -config /etc/secrets/dasconfig.json
   51 root      0:00 sh
   56 root      0:00 ps
/ # cat /data/run.sh
#!/bin/sh
mkdir -p /data/logs
nohup /data/das2go_exporter -address ":18217" 2>&1 1>& /data/logs/das2go_exporter.log < /dev/null &
/data/das2go -config /etc/secrets/dasconfig.json
```
So the main process is /data/run.sh which run exporter and das2go server. So, you may kill das2go process and I would expect that pod will not restart as exporter and run.sh are running.

2020-10-23 13:59 UTC, muhammadimranfarooqi commented
@vkuznet 

Actually, the container is killed with this. 

```
/ # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 {run.sh} /bin/sh /data/run.sh
    8 root      3:25 /data/das2go -config /etc/secrets/dasconfig.json
   45 root      0:00 sh
   53 root      0:00 ps aux
/ # kill -9 8
/ # command terminated with exit code 137
```

2020-10-26 11:56 UTC, vkuznet commented
@muhammadimranfarooqi , in this case the test can be performed by simply changing the end-point in livenessProbe, e.g. take `/das/bla-bla-bla` which does not exist and you'll get non 200 OK code.